### ISSUE TITLE
Problem compiling morph-streams

### ISSUE THREAD

**Issue by eugenesiow** [jpcik/morph-streams#3]
Hi,

I have some problem compiling morph-streams with sbt due to unresolved dependencies. The offending files are:
```
net.sf#jsqlparser;0.0.1
es.upm.fi.oeg.morph#kyrie;0.18.2
```
This seems to be a result of this artifactory repository, `http://aldebaran.dia.fi.upm.es/artifactory/`, being offline. Initially I had some problems with morph-core as well but I found an alternative repository `http://osper.epfl.ch:8081/artifactory/gsn-release/` that resolves this. 

Is there anyway around this, maybe a local repository? Although I can't find the `kyrie-0.18.2.pom`. 

Thanks!

**Comment by jpcik** [comment]
Hi,

Yes, it is true. I do not have control over aldebaran anymore, but I tried
to move all to osper.epfl.ch. I think i fixed all refs now.

2016-03-16 12:27 GMT+01:00 Eugene Siow <notifications@github.com>:

> Hi,
>
> I have some problem compiling morph-streams with sbt due to unresolved
> dependencies. The offending files are:
>
> net.sf#jsqlparser;0.0.1
> es.upm.fi.oeg.morph#kyrie;0.18.2
>
> This seems to be a result of this artifactory repository,
> http://aldebaran.dia.fi.upm.es/artifactory/, being offline. Initially I
> had some problems with morph-core as well but I found an alternative
> repository http://osper.epfl.ch:8081/artifactory/gsn-release/ that
> resolves this.
>
> Is there anyway around this, maybe a local repository? Although I can't
> find the kyrie-0.18.2.pom.
>
> Thanks!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jpcik/morph-streams/issues/3>
>



-- 
jp

**Comment by eugenesiow** [comment]
Thanks! It works fine now.
