### ISSUE TITLE
sbt stuck downloading dependencies

### ISSUE THREAD

**Issue by fediazgon** [jpcik/morph-streams#4]
When I try to build the project, sbt gets stuck while dumping the project structure. I think because is unable to fetch the dependencies from this urls:
```sbt
"aldebaran-releases" at "http://aldebaran.dia.fi.upm.es/artifactory/sstreams-releases-local",
"aldebaran-libs" at "http://aldebaran.dia.fi.upm.es/artifactory/sstreams-external-libs-local
```
For example, when trying to build the `query-rewriting` module. It cannot resolve the following dependency:
```sbt
"es.upm.fi.oeg.morph" % "morph-querygen" % "1.0.8"
```
However, if I try to build a project that does not download dependencies from the urls above, the build finishes. For example, I was able to build the `sparql-stream` module.

**Comment by jpcik** [comment]
Yes, those repositories are old and dead.
